version: 0.2

phases:
  install:
    commands:
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform
      - terraform -help
  build:
    commands:
      - terraform init  
#   post_build:
#     commands:
#       - echo Build completed on `date`
#       - mvn package
# artifacts:
#   files:
#     - target/my-app-1.0-SNAPSHOT.jar
#     - appspec.yml
#   discard-paths: yes
